/**
 * This class was designed as JavaBean for customers' records.
 * @author Alexandra Shapira
 */

package javaBeans;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

public class Customer {

	private String id;
	private String custName;
	private String password;
	private Set<Coupon> couponsOfCustomer = new HashSet<Coupon>();
	private boolean isActive = true;

	/**
	 * The class constructor that is used for creating a new Customer. It sets
	 * the unique id and isActive parameter as true (by default). Although the
	 * task includes an ID parameter of the long type it was decided to use the
	 * String type for this parameter in order to simplify getting the unique
	 * value.
	 * 
	 * @param custName
	 *            Company name
	 * @param password
	 *            password that the Company will use to access the application
	 * @param email
	 *            Company's email
	 */

	public Customer(String custName, String password) {
		this.id = UUID.randomUUID().toString();
		this.custName = custName;
		this.password = password;
	}

	/**
	 * The class constructor that is used to creating a new Customer object from
	 * the database record, therefore includes all Customer's parameters.
	 * 
	 * @param id
	 *            Customer's id
	 * @param custName
	 *            Customer's name
	 * @param password
	 *            password that the Customer will use to access the application
	 * @param couponsOfCustomer
	 *            the set of active coupons purchased by the Customer
	 * @param isActive
	 *            the state of the Company
	 */

	public Customer(String id, String custName, String password, Set<Coupon> couponsOfCustomer, boolean isActive) {
		this.id = id;
		this.custName = custName;
		this.password = password;
		this.couponsOfCustomer = couponsOfCustomer;
		this.isActive = isActive;
	}
	
	/**
	 * This constructor creates a Customer object with a unique id and empty
	 * attributes.
	 */

	public Customer() {
		this.id = UUID.randomUUID().toString();
		this.custName = "";
		this.password = "";
	}

	/**
	 * The method gets the Customer's's id.
	 * 
	 * @return Customer's id
	 */

	public String getId() {
		return id;
	}

	/**
	 * The method sets the id attribute.
	 * 
	 * @param id
	 *            Customer's id
	 */

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * The method gets the Customer's name.
	 * 
	 * @return Company's name
	 */

	public String getCustName() {
		return custName;
	}

	/**
	 * The method sets the Customer's name.
	 * 
	 * @param compName
	 *            Customer's name
	 */

	public void setCustName(String custName) {
		this.custName = custName;
	}

	/**
	 * The method gets the Customer's password.
	 * 
	 * @return Customer's password
	 */

	public String getPassword() {
		return password;
	}

	/**
	 * The method sets the Customer's password.
	 * 
	 * @param password
	 *            Customer's password
	 */

	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * The method gets the Customer's coupons.
	 * 
	 * @return Set of Coupons
	 */

	public Set<Coupon> getCouponsOfCustomer() {
		return couponsOfCustomer;
	}

	/**
	 * The method sets the Customer's coupons set.
	 * 
	 * @param couponsOfCustomer
	 */

	public void setCouponsOfCustomer(Set<Coupon> couponsOfCustomer) {
		this.couponsOfCustomer = couponsOfCustomer;
	}

	/**
	 * The method gets the Customer's state.
	 * 
	 * @return if company is active
	 */

	public boolean isActive() {
		return isActive;
	}

	/**
	 * The method gets the Customer's state.
	 * 
	 * @param isActive
	 *            if Customer is active
	 */

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	/**
	 * The method returns a string with all Customer's parameters
	 */

	@Override
	public String toString() {
		return "Customer: " + "\n" + "ID: " + id + "\n" + "Customer Name: " + custName + "\n" + "Password: " + password
				+ "\n" + "Coupons Of Customer: " + couponsOfCustomer + "\n" + "Is Active: " + isActive;
	}

	/**
	 * The autogenerated method that returns a hash code value for the object.
	 */

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((custName == null) ? 0 : custName.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * The method that indicates whether some other object is equal to this one.
	 */

	@Override
	public boolean equals(Object otherObject) {

		if (otherObject == null) {
			return false;
		}

		if (this == otherObject) {
			return true;
		}

		if (!(otherObject instanceof Customer)) {
			return false;
		}

		Customer otherCustomer = (Customer) otherObject;

		return (otherCustomer.getId() == this.id && otherCustomer.getCustName().equals(this.custName));
	}

}
